print('bilmece bildirmece, el üstünde kaydırmaca sabun. bu nedir?')
input()
print('sabun')
print()
print('şaban şimdi sıra sende konuş.')
print('ne diyeceeem?')
input()
print('merhaba lütfücüüüm..peki askerlere ne diyeceeemm?')
input()
print('haa merhaba ulan eskerelerr', end='')
print(' efferim')
